version: '3.9'
services:
  db:
    image: postgres:16
    container_name: nest_crud_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: nest_crud
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
    ports:
      - "3306:5432"
    volumes:
      - pgdata_data:/var/lib/postgresql/data

volumes:
  pgdata_data: